import { decodeUnicode } from './utils';

export const KOREAN_SHORTCUTS: Record<string, string> = {
  [`${decodeUnicode('⠫')}`]: '가',
  [`${decodeUnicode('⠉')}`]: '나',
  [`${decodeUnicode('⠊')}`]: '다',
  [`${decodeUnicode('⠑')}`]: '마',
  [`${decodeUnicode('⠘')}`]: '바',
  [`${decodeUnicode('⠇')}`]: '사',
  [`${decodeUnicode('⠨')}`]: '자',
  [`${decodeUnicode('⠋')}`]: '카',
  [`${decodeUnicode('⠓')}`]: '타',
  [`${decodeUnicode('⠙')}`]: '파',
  [`${decodeUnicode('⠚')}`]: '하',
  [`${decodeUnicode('⠸')},${decodeUnicode('⠎')}`]: '것',
  [`${decodeUnicode('⠹')}`]: '억',
  [`${decodeUnicode('⠾')}`]: '언',
  [`${decodeUnicode('⠞')}`]: '얼',
  [`${decodeUnicode('⠡')}`]: '연',
  [`${decodeUnicode('⠳')}`]: '열',
  [`${decodeUnicode('⠻')}`]: '영',
  [`${decodeUnicode('⠭')}`]: '옥',
  [`${decodeUnicode('⠷')}`]: '온',
  [`${decodeUnicode('⠿')}`]: '옹',
  [`${decodeUnicode('⠛')}`]: '운',
  [`${decodeUnicode('⠯')}`]: '울',
  [`${decodeUnicode('⠵')}`]: '은',
  [`${decodeUnicode('⠮')}`]: '을',
  [`${decodeUnicode('⠟')}`]: '인',
  [`${decodeUnicode('⠠')},${decodeUnicode('⠻')}`]: '성',
  [`${decodeUnicode('⠨')},${decodeUnicode('⠻')}`]: '정',
  [`${decodeUnicode('⠰')},${decodeUnicode('⠻')}`]: '청',
};
