import { decodeUnicode } from './utils';

export const ENGLISH_ALPHABET: Record<number, string> = {
  [decodeUnicode('⠁')]: 'a',
  [decodeUnicode('⠃')]: 'b',
  [decodeUnicode('⠉')]: 'c',
  [decodeUnicode('⠙')]: 'd',
  [decodeUnicode('⠑')]: 'e',
  [decodeUnicode('⠋')]: 'f',
  [decodeUnicode('⠛')]: 'g',
  [decodeUnicode('⠓')]: 'h',
  [decodeUnicode('⠊')]: 'i',
  [decodeUnicode('⠚')]: 'j',
  [decodeUnicode('⠅')]: 'k',
  [decodeUnicode('⠇')]: 'l',
  [decodeUnicode('⠍')]: 'm',
  [decodeUnicode('⠝')]: 'n',
  [decodeUnicode('⠕')]: 'o',
  [decodeUnicode('⠏')]: 'p',
  [decodeUnicode('⠟')]: 'q',
  [decodeUnicode('⠗')]: 'r',
  [decodeUnicode('⠎')]: 's',
  [decodeUnicode('⠞')]: 't',
  [decodeUnicode('⠥')]: 'u',
  [decodeUnicode('⠧')]: 'v',
  [decodeUnicode('⠺')]: 'w',
  [decodeUnicode('⠭')]: 'x',
  [decodeUnicode('⠽')]: 'y',
  [decodeUnicode('⠵')]: 'z',
};
