export * from './utils';
export * from './choseong';
export * from './jungsong';
export * from './jongseong';
export * from './char_shortcut';
export * from './char_english';
export * from './number';
export * from './symbol';
export * from './indicators';

import { decodeUnicode } from './utils'

// ASCII Braille to Unicode mapping (Standard North American Braille ASCII)
// Reference: https://en.wikipedia.org/wiki/Braille_ASCII
export const ASCII_BRAILLE_MAP: Record<string, number> = {
  ' ': decodeUnicode('⠀'),
  '!': decodeUnicode('⠮'),
  '"': decodeUnicode('⠐'),
  '#': decodeUnicode('⠼'),
  '$': decodeUnicode('⠫'),
  '%': decodeUnicode('⠩'),
  '&': decodeUnicode('⠯'),
  '\'': decodeUnicode('⠄'),
  '(': decodeUnicode('⠷'),
  ')': decodeUnicode('⠾'),
  '*': decodeUnicode('⠡'),
  '+': decodeUnicode('⠬'),
  ',': decodeUnicode('⠠'),
  '-': decodeUnicode('⠤'),
  '.': decodeUnicode('⠨'),
  '/': decodeUnicode('⠌'),
  '0': decodeUnicode('⠴'),
  '1': decodeUnicode('⠂'),
  '2': decodeUnicode('⠆'),
  '3': decodeUnicode('⠒'),
  '4': decodeUnicode('⠲'),
  '5': decodeUnicode('⠢'),
  '6': decodeUnicode('⠖'),
  '7': decodeUnicode('⠶'),
  '8': decodeUnicode('⠦'),
  '9': decodeUnicode('⠔'),
  ':': decodeUnicode('⠱'),
  ';': decodeUnicode('⠰'),
  '<': decodeUnicode('⠣'),
  '=': decodeUnicode('⠿'),
  '>': decodeUnicode('⠜'),
  '?': decodeUnicode('⠹'),
  '@': decodeUnicode('⠈'),
  'A': decodeUnicode('⠁'),
  'B': decodeUnicode('⠃'),
  'C': decodeUnicode('⠉'),
  'D': decodeUnicode('⠙'),
  'E': decodeUnicode('⠑'),
  'F': decodeUnicode('⠋'),
  'G': decodeUnicode('⠛'),
  'H': decodeUnicode('⠓'),
  'I': decodeUnicode('⠊'),
  'J': decodeUnicode('⠚'),
  'K': decodeUnicode('⠅'),
  'L': decodeUnicode('⠇'),
  'M': decodeUnicode('⠍'),
  'N': decodeUnicode('⠝'),
  'O': decodeUnicode('⠕'),
  'P': decodeUnicode('⠏'),
  'Q': decodeUnicode('⠟'),
  'R': decodeUnicode('⠗'),
  'S': decodeUnicode('⠎'),
  'T': decodeUnicode('⠞'),
  'U': decodeUnicode('⠥'),
  'V': decodeUnicode('⠧'),
  'W': decodeUnicode('⠺'),
  'X': decodeUnicode('⠭'),
  'Y': decodeUnicode('⠽'),
  'Z': decodeUnicode('⠵'),
  '[': decodeUnicode('⠪'),
  '\\': decodeUnicode('⠳'),
  ']': decodeUnicode('⠻'),
  '^': decodeUnicode('⠘'),
  '_': decodeUnicode('⠸'),
  a: decodeUnicode('⠁'),
  b: decodeUnicode('⠃'),
  c: decodeUnicode('⠉'),
  d: decodeUnicode('⠙'),
  e: decodeUnicode('⠑'),
  f: decodeUnicode('⠋'),
  g: decodeUnicode('⠛'),
  h: decodeUnicode('⠓'),
  i: decodeUnicode('⠊'),
  j: decodeUnicode('⠚'),
  k: decodeUnicode('⠅'),
  l: decodeUnicode('⠇'),
  m: decodeUnicode('⠍'),
  n: decodeUnicode('⠝'),
  o: decodeUnicode('⠕'),
  p: decodeUnicode('⠏'),
  q: decodeUnicode('⠟'),
  r: decodeUnicode('⠗'),
  s: decodeUnicode('⠎'),
  t: decodeUnicode('⠞'),
  u: decodeUnicode('⠥'),
  v: decodeUnicode('⠧'),
  w: decodeUnicode('⠺'),
  x: decodeUnicode('⠭'),
  y: decodeUnicode('⠽'),
  z: decodeUnicode('⠵'),
  '{': decodeUnicode('⠪'),
  '|': decodeUnicode('⠳'),
  '}': decodeUnicode('⠻'),
  '~': decodeUnicode('⠘'),
};
